import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../constants/app_constants.dart';
import '../models/match_model.dart';
import '../models/player_model.dart';

class PdfService {
  static Future<void> generateAndShareMatchPdf(
    MatchModel match,
    Map<String, PlayerModel> players,
  ) async {
    final pdf = pw.Document();

    // Load custom fonts if needed, but standard ones are fine for now
    // final font = await rootBundle.load("assets/fonts/Inter-Regular.ttf");
    // final ttf = pw.Font.ttf(font);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        '${AppConstants.appName.toUpperCase()} SCORECARD',
                        style: pw.TextStyle(
                          fontSize: 24,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.green900,
                        ),
                      ),
                      pw.Text(
                        match.title,
                        style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700),
                      ),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                        match.groundName.isNotEmpty ? match.groundName : 'Local Ground',
                        style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                      ),
                      pw.Text(
                        match.completedAt != null 
                          ? '${match.completedAt!.day}/${match.completedAt!.month}/${match.completedAt!.year}'
                          : '${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
                        style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // Result Card
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.green50,
                borderRadius: pw.BorderRadius.circular(8),
                border: pw.Border.all(color: PdfColors.green200),
              ),
              child: pw.Center(
                child: pw.Text(
                  match.result ?? 'Match Completed',
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.green800,
                  ),
                ),
              ),
            ),

            pw.SizedBox(height: 30),

            // Innings 1
            _buildInningsSection(
              match.teamAName,
              match.teamAScore,
              match.teamAPlayers.map((id) => players[id]).whereType<PlayerModel>().toList(),
              players.values.where((p) => p.teamId == 'B' && p.totalBowlingBalls > 0).toList(),
              players,
            ),

            pw.SizedBox(height: 40),

            // Innings 2
            _buildInningsSection(
              match.teamBName,
              match.teamBScore,
              match.teamBPlayers.map((id) => players[id]).whereType<PlayerModel>().toList(),
              players.values.where((p) => p.teamId == 'A' && p.totalBowlingBalls > 0).toList(),
              players,
            ),

            pw.SizedBox(height: 40),
            
            // Footer
            pw.Divider(),
            pw.SizedBox(height: 10),
            pw.Center(
              child: pw.Text(
                'Generated by ${AppConstants.appName} App • ${AppConstants.developedBy}',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500, fontStyle: pw.FontStyle.italic),
              ),
            ),
          ];
        },
      ),
    );

    // Save and Share
    final output = await getTemporaryDirectory();
    // Clean filename for filesystem
    final safeTitle = match.title.replaceAll(RegExp(r'[<>:"/\\|?*]'), '_');
    final file = File("${output.path}/$safeTitle.pdf");
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'Check out this match scorecard: ${match.title}',
    );
  }

  static pw.Widget _buildInningsSection(
    String teamName,
    MatchScore score,
    List<PlayerModel> batsmen,
    List<PlayerModel> bowlers,
    Map<String, PlayerModel> players,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        // Innings Header
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
          decoration: pw.BoxDecoration(
            color: PdfColors.blueGrey800,
            borderRadius: pw.BorderRadius.circular(4),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                teamName.toUpperCase(),
                style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold),
              ),
              pw.Text(
                '${score.runs}/${score.wickets} (${score.oversDisplay} ov)',
                style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold),
              ),
            ],
          ),
        ),

        pw.SizedBox(height: 10),

        // Batting Table
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(4),
            1: const pw.FixedColumnWidth(30),
            2: const pw.FixedColumnWidth(30),
            3: const pw.FixedColumnWidth(30),
            4: const pw.FixedColumnWidth(30),
            5: const pw.FixedColumnWidth(40),
          },
          children: [
            // Table Header
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey100),
              children: [
                _pdfHeaderCell('BATTING'),
                _pdfHeaderCell('R'),
                _pdfHeaderCell('B'),
                _pdfHeaderCell('4s'),
                _pdfHeaderCell('6s'),
                _pdfHeaderCell('SR'),
              ],
            ),
            // Table Rows
            ...batsmen.map((p) => pw.TableRow(
              children: [
                pw.Padding(
                  padding: const pw.EdgeInsets.all(6),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(p.name, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                      pw.Text(_getDismissalText(p, players), style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
                    ],
                  ),
                ),
                _pdfDataCell('${p.runsScored}'),
                _pdfDataCell('${p.ballsFaced}'),
                _pdfDataCell('${p.fours}'),
                _pdfDataCell('${p.sixes}'),
                _pdfDataCell(p.strikeRate.toStringAsFixed(1)),
              ],
            )),
          ],
        ),

        pw.SizedBox(height: 10),

        // Extras Row
        pw.Container(
          padding: const pw.EdgeInsets.all(6),
          child: pw.Text(
            'Extras: ${score.extras} (wd ${score.wides}, nb ${score.noBalls}, b ${score.byes}, lb ${score.legByes})',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
        ),

        pw.SizedBox(height: 15),

        // Bowling Table
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(4),
            1: const pw.FixedColumnWidth(35),
            2: const pw.FixedColumnWidth(35),
            3: const pw.FixedColumnWidth(30),
            4: const pw.FixedColumnWidth(30),
            5: const pw.FixedColumnWidth(40),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey100),
              children: [
                _pdfHeaderCell('BOWLING'),
                _pdfHeaderCell('O'),
                _pdfHeaderCell('R'),
                _pdfHeaderCell('W'),
                _pdfHeaderCell('Wd'),
                _pdfHeaderCell('Econ'),
              ],
            ),
            ...bowlers.map((p) => pw.TableRow(
              children: [
                pw.Padding(
                  padding: const pw.EdgeInsets.all(6),
                  child: pw.Text(p.name, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                ),
                _pdfDataCell(p.oversBowledDisplay),
                _pdfDataCell('${p.runsConceded}'),
                _pdfDataCell('${p.wicketsTaken}'),
                _pdfDataCell('${p.widesBowled}'),
                _pdfDataCell(p.economyRate.toStringAsFixed(1)),
              ],
            )),
          ],
        ),
      ],
    );
  }

  static pw.Widget _pdfHeaderCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
        textAlign: pw.TextAlign.center,
      ),
    );
  }

  static pw.Widget _pdfDataCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: const pw.TextStyle(fontSize: 10),
        textAlign: pw.TextAlign.center,
      ),
    );
  }

  static String _getDismissalText(PlayerModel player, Map<String, PlayerModel> players) {
    if (!player.isOut) {
      return player.ballsFaced > 0 ? 'not out' : '';
    }
    if (player.dismissalType == null || player.dismissalType!.isEmpty) return 'out';

    final type = player.dismissalType!;
    final bowlerName = player.dismissedBy != null && player.dismissedBy!.isNotEmpty
        ? (players[player.dismissedBy!]?.name ?? 'Unknown Bowler')
        : '';

    final typeLower = type.toLowerCase();
    if (typeLower.startsWith('caught')) {
      final fielderMatches = RegExp(r'\((.*?)\)').firstMatch(type);
      final fielderName = fielderMatches?.group(1);
      if (fielderName != null) {
        return bowlerName.isNotEmpty ? 'c $fielderName b $bowlerName' : 'c $fielderName';
      }
      return bowlerName.isNotEmpty ? 'c ? b $bowlerName' : 'caught';
    } else if (typeLower == 'bowled') {
      return 'b $bowlerName';
    } else if (typeLower == 'lbw') {
      return 'lbw b $bowlerName';
    } else if (typeLower == 'stumped') {
      return 'st b $bowlerName';
    } else if (typeLower == 'run out' || typeLower == 'run_out') {
      return 'run out';
    } else {
      return type.replaceAll('_', ' ') + (bowlerName.isNotEmpty ? ' b $bowlerName' : '');
    }
  }
}
