// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCy4Pa8O3hfz0S3JCd-Qpz6BMDCfB6fNg',
    appId: '1:82559395274:web:0129ad16c0e568c610db33',
    messagingSenderId: '82559395274',
    projectId: 'boxcricketapp-e9a33',
    authDomain: 'boxcricketapp-e9a33.firebaseapp.com',
    databaseURL: 'https://boxcricketapp-e9a33-default-rtdb.firebaseio.com',
    storageBucket: 'boxcricketapp-e9a33.firebasestorage.app',
    measurementId: 'G-0FL52LX0ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23DrIaIO-dkB94nlZzbPNqwaAHi_E3O4',
    appId: '1:82559395274:android:5715b79c7ce85b1410db33',
    messagingSenderId: '82559395274',
    projectId: 'boxcricketapp-e9a33',
    databaseURL: 'https://boxcricketapp-e9a33-default-rtdb.firebaseio.com',
    storageBucket: 'boxcricketapp-e9a33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUZykGDnb9hVu91E5tF23rsPfebjtO_c',
    appId: '1:82559395274:ios:d4c6d2030f31d03a10db33',
    messagingSenderId: '82559395274',
    projectId: 'boxcricketapp-e9a33',
    databaseURL: 'https://boxcricketapp-e9a33-default-rtdb.firebaseio.com',
    storageBucket: 'boxcricketapp-e9a33.firebasestorage.app',
    iosClientId: '82559395274-v1jg4gunudhv0i3jf0o288sjbnmket6s.apps.googleusercontent.com',
    iosBundleId: 'com.boxcricket.boxCricket',
  );
}
